# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_yandex_maps', '0002_load_init_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placemark',
            options={'verbose_name': 'Placemark', 'verbose_name_plural': 'Placemarks'},
        ),
        migrations.AlterModelOptions(
            name='yandexmaps',
            options={'verbose_name': 'Yandex Maps'},
        ),
        migrations.RemoveField(
            model_name='yandexmaps',
            name='auto_size',
        ),
        migrations.AddField(
            model_name='yandexmaps',
            name='jq_event',
            field=models.CharField(choices=[('blur', 'Blur'), ('change', 'Change'), ('click', 'Click'), ('contextmenu', 'Contextmenu'), ('dblclick', 'Dblclick'), ('focus', 'Focus'), ('focusin', 'Focusin'), ('focusout', 'Focusout'), ('hover', 'Hover'), ('keydown', 'Keydown'), ('keypress', 'Keypress'), ('keyup', 'Keyup'), ('load', 'Load'), ('mousedown', 'Mousedown'), ('mouseenter', 'Mousedown'), ('mouseleave', 'Mouseleave'), ('mousemove', 'Mousemove'), ('mouseout', 'Mouseout'), ('mouseover', 'Mouseover'), ('mouseup', 'Mouseup'), ('scroll', 'Scroll'), ('select', 'Select'), ('submit', 'Submit')], default='click', max_length=15, verbose_name='jQuery event'),
        ),
        migrations.AddField(
            model_name='yandexmaps',
            name='jq_selector',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='jQuery selector'),
        ),
        migrations.AddField(
            model_name='yandexmaps',
            name='size_update_method',
            field=models.CharField(blank=True, choices=[('observer', 'MutationObserver'), ('jq_event', 'jQuery event')], help_text='MutationObserver may be slow,not all events work, enable only if work not proper with hidden object', max_length=8, null=True, verbose_name='Size update method'),
        ),
        migrations.AddField(
            model_name='yandexmaps',
            name='sizing',
            field=models.CharField(choices=[('aspect', 'Keep aspect'), ('static', 'Static'), ('auto', 'Auto')], default='aspect', max_length=6, verbose_name='Sizing'),
        ),
        migrations.AlterField(
            model_name='placemark',
            name='balloonBody',
            field=models.TextField(blank=True, help_text='Replace "Balloon content". Can use some html, please be careful!', verbose_name='Balloon body'),
        ),
        migrations.AlterField(
            model_name='placemark',
            name='icon_glif',
            field=models.CharField(choices=[('Home', 'Home'), ('Airport', 'Airport'), ('Bar', 'Bar'), ('Food', 'Food'), ('Cinema', 'Cinema'), ('MassTransit', 'Mass Transit'), ('Toilet', 'Toilet'), ('Beach', 'Beach'), ('Zoo', 'Zoo'), ('Underpass', 'Underpass'), ('Run', 'Run'), ('Bicycle', 'Bicycle'), ('Bicycle2', 'Bicycle2'), ('Garden', 'Garden'), ('Observation', 'Observation'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Theater', 'Theater'), ('Book', 'Book'), ('Waterway', 'Waterway'), ('RepairShop', 'Repair Shop'), ('Post', 'Post'), ('WaterPark', 'Water Park'), ('Worship', 'Worship'), ('Fashion', 'Fashion'), ('Waste', 'Waste'), ('Money', 'Money'), ('Hydro', 'Hydro'), ('Science', 'Science'), ('Auto', 'Auto'), ('Shopping', 'Shopping'), ('Sport', 'Sport'), ('Video', 'Video'), ('Railway', 'Railway'), ('Park', 'Park'), ('Pocket', 'Pocket'), ('NightClub', 'Night Club'), ('Pool', 'Pool'), ('Medical', 'Medical'), ('Vegetation', 'Vegetation'), ('Government', 'Government'), ('Circus', 'Circus'), ('RapidTransit', 'Rapid Transit'), ('Education', 'Education'), ('Mountain', 'Mountain'), ('CarWash', 'Car Wash'), ('Factory', 'Factory'), ('Court', 'Court'), ('Hotel', 'Hotel'), ('Christian', 'Christian'), ('Laundry', 'Laundry'), ('Souvenirs', 'Souvenirs'), ('Dog', 'Dog'), ('Leisure', 'Leisure')], default='Home', max_length=30, verbose_name='Icon glif'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='auto_placement',
            field=models.BooleanField(default=True, help_text='Automatically find the center and zoom', verbose_name='Auto placement'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='behaviors',
            field=models.ManyToManyField(default=(1, 2, 3, 4, 6), help_text="Sorry for the Russian, I'm too lazy and just copied the description from the documentation", to='cmsplugin_yandex_maps.Behavior', verbose_name='Behaviors'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='cluster_disable_click_zoom',
            field=models.BooleanField(default=True, verbose_name='Disable cluster click zoom'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='controls',
            field=models.ManyToManyField(default=(5, 6, 7), help_text="Sorry for the Russian, I'm too lazy and just copied the description from the documentation", to='cmsplugin_yandex_maps.Control', verbose_name='Controls'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='height',
            field=models.IntegerField(default=180, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='yandexmaps',
            name='width',
            field=models.IntegerField(default=320, verbose_name='Width'),
        ),
    ]
